[workspace]
members = [
    "crates",
    "examples/chess",
    "examples/hex_map",
    "examples/market",
    "examples/projectile",
    "token",
]

[workspace.package]
version = "0.5.0"
description = "Community-maintained libraries for Cairo"
homepage = "https://github.com/dojoengine/origami"
authors = ["bal7hazar@proton.me"]

[workspace.dependencies]
cubit = { git = "https://github.com/akhercha/cubit.git", rev = "d3869a3" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.5.0" }
origami = { path = "crates" }
token = { path = "token" }
