[workspace]
members = [
    "crates",
    "examples/chess",
    "examples/hex_map",
    "examples/market",
    "examples/projectile",
    "token",
]

[workspace.package]
version = "0.6.0-alpha.6"
description = "Community-maintained libraries for Cairo"
homepage = "https://github.com/dojoengine/origami"
authors = ["bal7hazar@proton.me"]

[workspace.dependencies]
# cubit = { git = "https://github.com/influenceth/cubit.git" }
cubit = { git = "https://github.com/notV4l/cubit.git", rev = "5aa99005" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0-alpha.6" }
origami = { path = "crates" }
token = { path = "token" }
