kind = "DojoContract"
class_hash = "0x4cb3d7ebb682804fb651db0472bda817dec4eb0c12e6fa66db2e14487a73305"
abi = "abis/base/contracts/actions.json"
reads = []
writes = []
computed = []
name = "chess::actions::actions"
