kind = "DojoModel"
class_hash = "0x597ed2b0715a510c3258e1f6dc631177dac7a0f73a40bcc3d568cdf2e884e9e"
name = "token::erc20::models::erc_20_balance"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "account"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u256"
key = false
