kind = "DojoModel"
class_hash = "0x7d11cbbc60a2e505706cd53742412f921dd910837aa2e55937eaef66055036c"
name = "token::erc20::models::erc_20_allowance"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "spender"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u256"
key = false
