kind = "DojoModel"
class_hash = "0x2d779aa4e9abb941a2d030fe986ef3008fd2152ec8e6809cbbc0058d266ee6f"
name = "token::components::token::erc20::erc20_bridgeable::erc_20_bridgeable_model"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "l2_bridge_address"
type = "ContractAddress"
key = false
